---
# vars file for azure-rg-config

# Required parameters
res_group: "{{ res_group }}"
project_name: "{{ project_name }}"

# Azure subscription values
azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID')}}"
azure_tenant: "{{ lookup('env', 'AZURE_TENANT')}}"
azure_subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID')}}"
azure_secret: "{{ lookup('env', 'AZURE_SECRET')}}"

# Default values
res_group_location: eastus
storage_account: "lrsansibledemo"
storage_class: Standard_LRS
storage_blob: "ansibledemo.vhd"
virtual_network: "{{ project_name }}-vnet"
virtual_network_cidr: 10.0.0.0/24
subnet: "{{ project_name }}-subnet"
subnet_cidr: 10.0.0.0/24

